pipeline {
  agent any
  environment {
    BUCKET = 'assalamualaikum-serverless-go-bucket'
  }
  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/kandlagifari/go-serverless.git'
      }
    }
    stage('Testing 1') {
      steps {
        sh "ls && pwd"
        sh "cd ./06_cicd-pipeline/01_jenkins-cicd/findAll"
        sh "ls && pwd"
      }
    }
    stage('Testing 2') {
      steps {
        sh "aws s3 ls s3://$BUCKET --endpoint-url=http://localstack:4566"
        sh "ls && pwd"
        sh "cd ./06_cicd-pipeline/01_jenkins-cicd/findAll"
        sh "ls && pwd"
      }
    }
  }
}